// <auto-generated />
namespace HomeWork1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class HomeController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HomeController));
        
        string IMigrationMetadata.Id
        {
            get { return "202004111631054_Home Controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
