// <auto-generated />
namespace HomeWork1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Aboutaddettoresumeclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aboutaddettoresumeclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202004101915599_About addet to resume class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
